In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('/content/i2.csv')

In [4]:
df.head()

,Date,Timestamp,Invoice No.,Item Name,Price,Qty.,Sub Total,Discount,Tax,Final Total,Table No.,Server Name,Covers,Variation,Category,HSN
0,2023-06-30,2023-06-30 22:47:50,26190,Mineral Water,20.0,1.0,20.0,0.0,1.0,21.0,1.0,biller,0,NaN,Deserts & Mocktails,NaN
1,2023-06-30,2023-06-30 22:25:11,26189,Chapathi (2 No),50.0,1.0,50.0,0.0,2.5,52.5,9.0,biller,0,NaN,Indian Breads,NaN
2,2023-06-30,2023-06-30 22:25:11,26189,Roti,40.0,1.0,40.0,0.0,2.0,42.0,9.0,biller,0,NaN,Indian Breads,NaN
3,2023-06-30,2023-06-30 22:25:11,26189,Mushroom Pulao,140.0,1.0,140.0,0.0,7.0,147.0,9.0,biller,0,NaN,VEG BIRYANI & RICE,NaN
4,2023-06-30,2023-06-30 22:25:11,26189,Veg Fried Rice,130.0,1.0,130.0,0.0,6.5,136.5,9.0,biller,0,NaN,VEG BIRYANI & RICE,NaN

In [5]:
df.tail()

,Date,Timestamp,Invoice No.,Item Name,Price,Qty.,Sub Total,Discount,Tax,Final Total,Table No.,Server Name,Covers,Variation,Category,HSN
8374,2023-04-01,2023-04-01 13:16:03,23465,Paneer Butter Masala,150.0,2.0,300.0,0.0,15.0,315.0,20.0,biller,0,NaN,Veg Gravy,NaN
8375,2023-04-01,2023-04-01 13:16:03,23465,Schewan Chicken Fried Rice,160.0,1.0,160.0,0.0,8.0,168.0,20.0,biller,0,NaN,NON VEG BRIYANI & RICE,NaN
8376,2023-04-01,2023-04-01 13:16:03,23465,Schezwan Egg Fried Rice,140.0,1.0,140.0,0.0,7.0,147.0,20.0,biller,0,NaN,NON VEG BRIYANI & RICE,NaN
8377,2023-04-01,2023-04-01 13:16:03,23465,Chicken Kati Roll,120.0,1.0,120.0,0.0,6.0,126.0,20.0,biller,0,NaN,NON VEG STARTERS CHICKEN,NaN
8378,2023-04-01,2023-04-01 13:16:03,23465,Soft Drink 600ml,40.0,2.0,80.0,0.0,4.0,84.0,20.0,biller,0,NaN,Deserts & Mocktails,NaN

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8379 entries, 0 to 8378
Data columns (total 16 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         8379 non-null   object
 1   Timestamp    8379 non-null   object
 2   Invoice No.  8379 non-null   int64
 3   Item Name    8379 non-null   object
 4   Price        8379 non-null   float64
 5   Qty.         8379 non-null   float64
 6   Sub Total    8379 non-null   float64
 7   Discount     8379 non-null   float64
 8   Tax          8379 non-null   float64
 9   Final Total  8379 non-null   float64
 10  Table No.    8371 non-null   float64
 11  Server Name  8379 non-null   object
 12  Covers       8379 non-null   int64
 13  Variation    7 non-null      object
 14  Category     8379 non-null   object
 15  HSN          0 non-null      float64
dtypes: float64(8), int64(2), object(6)
memory usage: 1.0+ MB

In [7]:
df.describe()

,Invoice No.,Price,Qty.,Sub Total,Discount,Tax,Final Total,Table No.,Covers,HSN
count,8379.000000,8379.000000,8379.000000,8379.000000,8379.000000,8379.000000,8379.000000,8371.000000,8379.0,0.0
mean,24828.808927,111.161594,1.306958,136.245733,1.108451,6.749999,141.887281,16.278461,0.0,NaN
std,771.793237,65.076360,0.949960,257.877211,6.658616,12.845963,269.751689,16.129123,0.0,NaN
min,23465.000000,12.000000,1.000000,12.000000,0.000000,0.000000,12.600000,1.000000,0.0,NaN
25%,24173.000000,50.000000,1.000000,60.000000,0.000000,3.000000,63.000000,4.000000,0.0,NaN
50%,24830.000000,120.000000,1.000000,140.000000,0.000000,6.760000,141.760000,11.000000,0.0,NaN
75%,25491.500000,160.000000,1.000000,170.000000,0.000000,8.500000,178.500000,20.000000,0.0,NaN
max,26190.000000,770.000000,28.000000,21560.000000,192.000000,1078.000000,22638.000000,50.000000,0.0,NaN

In [8]:
df.shape

(8379, 16)

In [9]:
df.isnull().sum()

Date              0
Timestamp         0
Invoice No.       0
Item Name         0
Price             0
Qty.              0
Sub Total         0
Discount          0
Tax               0
Final Total       0
Table No.         8
Server Name       0
Covers            0
Variation      8372
Category          0
HSN            8379
dtype: int64

In [10]:
df['Invoice No.'].unique()

array([26190, 26189, 26188, ..., 23467, 23466, 23465])

In [11]:
df['Invoice No.'].nunique()

2726

In [12]:
df['Item Name'].unique()

array(['Mineral Water', 'Chapathi (2 No)', 'Roti', 'Mushroom Pulao',
       'Veg Fried Rice', 'Butter Scotch Scoop', 'Paneer Manchurian',
       'Thandoor Chicken Full', 'Schezwan Chicken  Fried Rice',
       'Sweet Corn Chicken Soup', 'Chicken Noodles', 'Lemon Soda',
       'Pepper Garlic Chicken Soup', 'Mushroom - 65', 'Chicken Lolly Pop',
       'French Fries', 'Chicken Fried Rice', 'Chicken 65', 'Butter Naan',
       'Dragon Chicken', 'Paneer Butter Masala', 'Kadai Chicken',
       'Soft Drink 600ml', 'Tea', 'Kozhicharru', 'Prawn Noodles',
       'Schezwan Paneer', 'Chicken Biriyani With Raitha And Gravy',
       'Egg Briyani With Raitha And Chicken Gravy',
       'Schewan Veg Fried Rice', 'Gobi- 65', 'Blue Lagoon',
       'Mixed Veg Pulao', 'Baby Corn 65', 'Chicken Manchurian Dry',
       'Prawn 65', 'Fish Finger', 'Pichi Potta Kozhi Varuval',
       'Schezwan Chicken Dry', 'Egg Noodles', 'Mixed Fried Rice',
       'Schewan  Chicken Fried Rice', 'Plain Briyani With Raitha, Gravy.',
       'Mint Lemon Juice', 'Gobi Manchurian',
       'Pepper Tandoori Chicken ( Half )', 'Kadai Paneer', 'Naan',
       'Veg Noodles', 'Egg Fried Rice', 'Thandoor Chicken Half',
       'Schewan Chicken Noodle', 'Dragon Mushroom', 'Paneer Fried Rice',
       'Pulka (2 No)', 'Kozhi Milaghuperattal', 'Chicken Kheema Masala',
       'Pepper Chicken Gravy', 'Fish 65', 'Hot And Sour Veg Soup',
       'Paneer- 65', 'Jeera Peas Pulao', 'Chettinad Mushroom Masala',
       'Strawberry Scoop', 'Fresh Lemon Juice',
       'Hydrabadi Chicken Masala', 'Pepper Tandoori Chicken ( Full )',
       'Butter Chicken Gravy', 'Butterscotch Milk Shake',
       'Oreo Milk Shake', 'Romali Roti (1 No)',
       'Tandoor Chicken ( Quarter)', 'Venilla Scoop', 'Manchow Veg Soup',
       'Manchow Chicken Soup', 'Chicken Chettinad',
       'Sesame Fried Chicken', 'Chicken 65 Boneless',
       'Kozhi Malliperattal', 'Hot And Sour Chicken Soup', 'Egg Bhurji',
       'Schezwan Egg Fried Rice', 'Manchurian Gravy (Gobi)',
       'Dragon Babycorn', 'Honey Potato', 'Singapore Fried Rice Veg',
       'Chicken Kati Roll', 'Mint Lime Soda', 'Prawn Biriyani',
       'Nethili Fish Fry', 'Sweet Corn Veg Soup', 'Prawn Fried Rice',
       'Mixed Noodles', 'Karaikudi Chicken', 'Gulab Jamun', 'Kalaki',
       'Kanniyakumari Fish Fry', 'Tandoori Paratha', 'Mixed Veg Curry',
       'Singapore Noodles Non-veg', 'Dragon Prawns', 'Curd Rice',
       'Mushroom Fried Rice', 'Butter Roti', 'Egg Bhurji Masala',
       'Schezwan Prawn Fried Rice', 'Kozhi Sukka', 'Chocolate Scoop',
       'Chilly Fish Dry', 'Karaikudi Kozhi Kozhimbu', 'Mojito',
       'Prawn Pepper And Salt', 'Strawberry Milk Shake',
       'Babycorn Manchurian', 'Kulcha', 'Garlic Naan',
       'Plain Paratha (1 No)', 'Mushroom Gravy', 'Veg Kuruma',
       'Singapore Noodles Veg', 'Schezwan Mushroom',
       'Chocolate Milk Shake', 'Chilly Chicken Dry', 'Chicken Roast',
       'Tawa Fried Fish', 'Kadai Vegetable', 'Potato 65', 'Ghee Rice',
       'Potato Manchurian', 'Masala Omelet (two Eggs',
       'Chilly Gobi (chinese)', 'Full Boil', 'Chicken Pallipalayam Gravy',
       'Mixed Chilly Vegetable', 'Mushroom Masala', 'Prawn Manchurian',
       'Methi Chicken Masala', 'Schezwan Veg Noodles', 'Bulls Eye',
       'Green Peas  Masala', 'Gobi Mushroom', 'Boiled Egg (2 Nos)',
       'Chicken Pallipalayam', 'Jeera Rice', 'Vegetable Pepper Soup',
       'Kheema Paneer', 'Pepper Jeeraga Chicken', 'Chilly Chicken Gravy',
       'Egg Masala', 'Prawn Pepper Fry', 'Dragon Paneer',
       'Pichipotta Kozhivaruval', 'Veg Pulao', 'Prawns Schezwan Noodles',
       'Chicken Manchurian Gravy', 'Paneer Pulao', 'Mushroom Manchurian',
       'Paneer Noodles', 'Chicken Tikka', 'Pepper Thandoor (quarter)',
       'Egg Pepper Fry', 'Butter Kulcha', 'Soda 750ml',
       'Singapore Fried Rice Non-veg', 'Egg Roll', 'Veg Clear Soup',
       'Kadai Mushroom', 'Ice Cream With Jamun', 'Fish Manchurian Dry',
       'Schezwan Paneer Fried Rice', 'Schewan Egg Noodle',
       'Chicken Clear Soup', 'Schezwan Fish Dry', 'Oreo Scoop',
       'Kumpo Chicken', 'Channa Masala', 'Venila Milk Shake',
       'Black Current Scoop', 'Dal Tudka', 'Baby Corn Pepper Fry',
       'Butter Milk', 'Kadai Prawns', 'Dragon Fish',
       '1 Indian Combo - Welcome Drink, Chicken Dum Biriyani, Onion Raita, Chicken Gravy, Boiled Egg, Chicke',
       'Tandoori Bread Combo - Welcome Drink, Butter Naan/ Butter Roti, Butter Chicken Masala, Chicken-65, I',
       'Mushroom Biriyani', 'Tandoor Chicken Quater',
       'Chilly Mushroom(chinese)', 'Schezwan Gobi', 'Aalu Gobi Masala',
       'Black Current Milkshake', 'Lemon Terror', 'Mutton Sukka',
       'Green Peas  Mushroom  Masala', 'Kumpo Fish Dry',
       'Schezwan Chicken Gravy', 'Water Bottle 500 Ml', 'Tawa Paratha',
       'Kadai Vegetables', 'Manchurian Gravy (Babycorn)',
       'Ygr Special Chicken', 'Mutton Biriyani', 'Lessi Salt',
       'Chilli Paneer', 'Prawn Chilli', 'Schezwan Prawn',
       'Soft Drink 250ml', 'Paneer Do Pyaza',
       'Schezwan Mushroom Fried Rice',
       'Tandoori Bread Combo - Welcome Drink, Butter Naan/ Butter Roti, Paneer Butter Masala, Gobi - 65, Ice',
       'Pista Scoop', 'Dragon Gobi',
       'Chinese Combo - Welcome Drink, Chicken Fried Rice/ Chicken Noodles, Tomato Sauce, Chilly Sauce, Gobi',
       'Schezwan Gravy (Gobi)', 'Schezwan Gravy (Babycorn)',
       'Chicken Kathi Roll', 'Veg Pulav', 'Egg Buriji',
       'Packed Lunch Non-veg Combo', 'Pepper Chicken Boneless',
       'Schewan Noodles', 'Chilly Potato'], dtype=object)

In [13]:
df['Item Name'].nunique()

222

In [14]:
df['Final Total'].sum()

1188873.53

In [15]:
df['Final Total'].sum() / df['Invoice No.'].nunique()

436.12381878209834

In [16]:
df['Discount'].sum()

9287.71

In [17]:
df['Tax'].sum()

56558.24

In [20]:
a =df['Discount'].sum() / df['Invoice No.'].nunique()
print(a)

3.4070836390315478